"""create bookings table

Revision ID: b4ee87514629
Revises:
Create Date: 2026-08-26 03:00:57.642282

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b4ee87514629"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
